### ISSUE TITLE
Bokeh vs. Altair as visualization library

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#86]
I was wondering what factors have been considered in order to choose Altair as the visualization library for this project. To me, Bokeh seems to have a much easier syntax, it's equally feature-rich, and also more popular compared to Altair. I would appreciate if some feedback on this could be provided. Thanks!

**Comment by koaning** [comment]
A lot of it comes down to taste: I just felt that altair looked nicer so that is what I've implemented. I should also say that I really like their `&` and `|` operators to chain charts together. 

There may be some merit to also implementing bokeh though. I'm certainly open to supporting more than one backend and I can certainly imagine that that bokeh might scale more as we plot more points on charts (altair will fail after a couple of 1000). We offer matplotlib charts too at the moment but they are not interactive. 

I'm not opposed to bokeh support if folks are willing to contribute and can make a compelling case for it.
I don't feel the need to implement this myself at the moment though. The main reason is that 2d plots of reduced embeddings don't give *that* much information when you plot many points (example [here](https://nlp.h-its.org/bpemb/#visualization)) and if you don't have many points you might as well use altair.

**Comment by mkaze** [comment]
Thanks for your reply. Actually, I have no experience with Altair. But it seemed to me to be more complex compared to bokeh or matplotlib (maybe I am wrong). For example, I could not find any way in Altair to make the axes have equal scales (i.e. #38) so that some of the visualizations, such as orthogonal vectors, make more sense. However, I could easily achieve this with matplotlib or bokeh. Anyways, I agree that more justifiable reasons are needed to add the support for bokeh as well, since altair is almost working fine in current use cases.

I'll leave this issue open since someone else in the future would be able to add more points to this discussion and provide a compelling case for supporting bokeh.

**Comment by koaning** [comment]
I recall being able to do something like;

```python
alt.Chart(subset).mark_line().encode(
    X('Year', scale=Scale(domain=(2000, 2017))),
    y='Number of Papers'
)
```

No worries though, I might have a look at this issue later this week.

**Comment by ewirth** [comment]
I also started to look after the topic Altair vs. Bokeh. Definitely Bokeh seems thicker in code and solutions (html, png, etc.).
The simplicity of Altair is attractive, but it seems a bit rudimentary/experimental, e.g. I scanned the documentation, here is an example:
https://altair-viz.github.io/gallery/scatter_href.html
- If you check the label of Y axis, you can see 'Miles_per_Gallon' written instead of 'Miles/Gallon', in other examples you can't find a space in the labels (like 'sepalLenght'). So I suppose, that it's not implemented yet, then what will be with UTF characters?!

https://python.libhunt.com/compare-bokeh-vs-altair
- You can see Altair's activity is Declining.
- Altair doesn't have a Code quality mark even

I am not sure in that Altair is the proper choose.

**Comment by koaning** [comment]
Altair is based on top of [vega lite](https://vega.github.io/vega-lite/). I imagine the activity is less now because the project is nearing feature completeness for vega. I don't know what a "code quality" mark is but the Altair project has flake/black/pytest active so I'm not too worried about that. 

I still prefer to have Altair be the main interactive plotting engine simply because it is "less buttons to fiddle around with". You can pan and zoom at the same time and that's something I've never gotten to work properly using Bokeh. It's super simple to stack charts together using operators like `|` and `&` and the fact that you can export the json and host it is a big plus. 

The main feature that Bokeh offers is the ability to draw many datapoints without failing. That said, I don't think those charts are particularily useful. Here's an [example](https://nlp.h-its.org/bpemb/en/en.wiki.bpe.emb.vs200000.d300.html). It's too much of a congitive load to take it all in.

**Comment by koaning** [comment]
There's also tools like [plotly](https://plotly.com/python/3d-scatter-plots/#reference) that allow 3d plots. I've got a similar concern here as with the many datapoints chart in bokeh. It'll be a cool demo, sure. But there's a risk of cognitive overload.

**Comment by ewirth** [comment]
Just for your sake checked Altair again, I tested both. Altair seems to support accents, and spaces (but you can't specify to labels, you have to change the pandas dataframe variable names for that:

```
import altair as alt
import pandas as pd

data = pd.DataFrame({'Osztály kategória': ['A', 'B', 'C', 'D', 'E'],
                     'Arany / érték': [5, 3, 6, 7, 2]})
chart = alt.Chart(data).mark_bar().encode(
    x='Osztály kategória',
    y='Arany / érték',
)

chart.save('d:/altair-elections4.html')
```

Bokeh's code is definitely longer, but I find more freedom there, to specify my needs (like define label names explicitly).
I've already used Plot.ly JS/Python, but that's Freemium, and I prefer free open-source options, so I switched to Bokeh.

If you see my previous link, about comparison, I think you can't neglect that - numbers count a lot.


![image](https://user-images.githubusercontent.com/11816204/90111187-8cf0cb80-dd4e-11ea-9aab-6a80c3e9e21f.png)

**Comment by koaning** [comment]
> What a marketing bullshit; sounds like a bounded dataviz box; 'data scientist' should have a boundless thinking.

If you dislike a package, you're certainly allowed to. However I prefer the github threads remain polite. Most open source work is volunteer work so it's fair to expect some manner of respect here. If you prefer that this package also support another visualisation backend then I'm open to suggestions (you're even welcome to contribute) but we need a different tone of voice before we can engage in meaningful collaboration. 

Again; we're all doing volunteer work here, the least we can do is remain polite.

**Comment by koaning** [comment]
I think the user that I am quoting in the previous message has left? Anyhow. 

I've started wondering if we can abstract some of the plots away from the `EmbeddingSet`. There's two benefits to this:

1. The `EmbeddingSet` is getting big and it is nice to separate concern. 
2. By abstracting the plots away we might be able to support different backends more easily.

This is, to me at least, not very high on the priority list. I'd prefer to abstract/cleanup the transformers and languages first. But figured I'd put the idea here.

**Comment by mkaze** [comment]
> I've started wondering if we can abstract some of the plots away from the EmbeddingSet.

Do you mean you want to entirely remove the corresponding methods from `EmbeddingSet` class and change the API for plotting, or the methods will remain in the class and just the implementation would be delegated somehow to another module/mixin class/etc.?

**Comment by koaning** [comment]
I'm not 100% sure yet because in part this will depend on whether or not we want to accept other plotting backends. I currently do not have the overview to understand what parts are general across these libraries and what parts are specialised but we might end up with classes like; 


```
InteractivePlot(settings).plot_altair(embset)
InteractivePlot(settings).plot_bokeh(embset)
InteractivePlot(settings).plot_plotly(embset)

PlotDistance(settings).plot_matplotlib(embset)
PlotDistance(settings).plot_bokeh(embset)
PlotDistance(settings).plot_plotly(embset)
```

These could then be used internally in the EmbeddingSet or potentially outside of it as well. I'm not 100% sure if this is the best option, but the separation of concerns would be nice. 

That said, I'll probably work on the transformer/language abstraction first.

**Comment by koaning** [comment]
Alternatively, we might also be able to use [these sorts of tricks](https://fastpages.fast.ai/fastcore/#Monkey-Patching-With-A-Decorator).

**Comment by koaning** [comment]
I'm using bokeh a lot now for another project and ... I'm pretty convinced that it is epic. You can make some lovely interactive toys with it so I'm in favor of adding support now.

**Comment by koaning** [comment]
Since the repository moved to my personal account I'm moving this project into maintenance mode. This issue, while interesting, likely won't get the attention it needs in the future.
